version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
branches:
  only:
    - master
install:
  # 執行 nuget restore
  - cmd: nuget restore
configuration: Release
platform: Any CPU
build_script:
  # 使用 msbuild 編譯 WPF 程式，針對 Any CPU 組態編譯一個 Release 版本，並設定版本號
  - cmd: msbuild PasswordPocketHelper.sln /r /t:PasswordPocketHelper /p:Configuration=Release /p:Platform="Any CPU" /p:Version=%APPVEYOR_BUILD_VERSION%
after_build:
  # 壓縮已編譯的檔案和資料夾，並將壓縮檔命名為包含版本號的檔案名
  - 7z a PasswordPocketHelper_%APPVEYOR_BUILD_VERSION%.zip .\PasswordPocketHelper\bin\Release\net6.0-windows\* -r
test: off
deploy:
  - provider: GitHub
    auth_token:
      secure: ch7FMdMWY4hVoEkbwRZXiU+Sb//46oMHq/etzvmV7+TKY8VvMqd+YMYBH9NUaANG
    artifact: PasswordPocketHelper_%APPVEYOR_BUILD_VERSION%.zip
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: false       # deploy on tag push only
artifacts:
  - path: PasswordPocketHelper_%APPVEYOR_BUILD_VERSION%.zip
    name: PasswordPocketHelper
