version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- ps: msbuild PasswordPocketHelper.sln /r /t:PasswordPocketHelper /p:Configuration=Release /p:Platform="Any CPU" /p:Version=$APPVEYOR_BUILD_VERSION /p:FileVersion=$APPVEYOR_BUILD_VERSION
after_build:
  - 7z a PasswordPocketHelper_%APPVEYOR_BUILD_VERSION%.zip .\PasswordPocketHelper\bin\Release\net6.0-windows\* -r
test: off
deploy:
- provider: GitHub
  auth_token:
    secure: ch7FMdMWY4hVoEkbwRZXiU+Sb//46oMHq/etzvmV7+TKY8VvMqd+YMYBH9NUaANG
  artifact: /PasswordPocketHelper_%APPVEYOR_BUILD_VERSION%.zip
  on:
    branch: master